# Generated by Django 3.1 on 2020-08-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-date_created']},
        ),
    ]
