# Generated by Django 3.1 on 2020-08-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_search', '0002_auto_20200815_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['date_created']},
        ),
    ]
