# Generated by Django 3.1 on 2020-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_search', '0003_auto_20200815_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='error',
            field=models.CharField(default='', max_length=512),
        ),
    ]
