# Generated by Django 3.1 on 2020-08-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_search', '0005_auto_20200819_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='arrival_city',
            field=models.CharField(help_text='City of your destination', max_length=128),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='date_to',
            field=models.DateField(help_text='Last day of your availabilty'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='departure_city',
            field=models.CharField(help_text='Your current city', max_length=128),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='stay_duration',
            field=models.IntegerField(blank=True, help_text='*You will be given results &#177; 3 days from this number', null=True),
        ),
    ]
