name: Django CI

on:
  push:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: Running UnitTests

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: j6@(n&k&r9^z(30uil(4#)
        DEBUG: True
        ALLOWED_HOSTS: localhost
        REDIS_URL: redis://h:pc37c2d74da0343710e79ae5361754271d47c9e1dea3dff5112bcc3af8333dda1@ec2-54-90-127-248.compute-1.amazonaws.com:17159 
